"""build_harness.py — package the shipped frontend + a recorded fixture
bundle into a self-contained replay harness (HARNESS tooling, 2026-08-13).

    python tools/build_harness.py fixtures-2026-08-13.json --out harness/

The output folder opens offline — no server, no install, no network. The
designer copies it into the design project and clicks the actual UI.

Ground rules this script enforces:
  * app.js and styles.css are copied BYTE-IDENTICAL. If app.js needs a
    change to run in the harness, that is a finding to report, not a
    patch to apply.
  * index.html gets exactly the path rewrites (server-absolute ->
    relative) and the fixture script inserts. Nothing else.
  * Fixtures are recorded, never authored. This script serves back what
    the recorder captured, verbatim.
"""
from __future__ import annotations

import argparse
import json
import re
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
STATIC = ROOT / "app" / "static"
MAIN_PY = ROOT / "app" / "main.py"

# ------------------------------------------------------------------ shim
# Written into the harness as fixtures.js. %%PLACEHOLDER_SVG%% is filled
# at build time with a concrete-hex SVG (a standalone image cannot
# resolve CSS variables); everything else in the harness chrome (the
# staleness banner) CAN use var() because styles.css is loaded.
FIXTURES_JS = r"""/* fixtures.js — replay shim (generated by tools/build_harness.py).
   Serves the recorded bundle back to the shipped app.js, byte for byte.
   Fixtures are recorded, never authored — do not edit responses here. */
(() => {
  "use strict";
  const BUNDLE = window.__FIXTURES__;   // fixtures.data.js, loaded before this
  const HARNESS = window.__HARNESS__ || {};
  const MISSES = (window.__HARNESS_MISSES__ = []);

  const byKey = new Map();              // "GET /api/x" -> [entry, entry, …]
  for (const e of BUNDLE.entries) {
    if (!byKey.has(e.key)) byKey.set(e.key, []);
    byKey.get(e.key).push(e);
  }
  const cursor = new Map();

  // Known app↔server coupling (reported, not patched): syncUrl at
  // app.js:1621 writes server-absolute history URLs ("/status"), which
  // a file: origin refuses with SecurityError — uncaught, it kills
  // boot. The shim owns the environment, so it absorbs the throw;
  // navigation-by-click still works, which is what the harness is for.
  for (const m of ["pushState", "replaceState"]) {
    const realH = history[m].bind(history);
    history[m] = (...a) => {
      try { return realH(...a); }
      catch (e) { console.warn(`[harness] history.${m} suppressed:`, e.message); }
    };
  }

  const PLACEHOLDER_SVG = %%PLACEHOLDER_SVG%%;
  const IMG_RE = /\.(png|jpe?g|gif|webp|svg|avif)([?#]|$)/i;

  const svgResponse = () => new Response(PLACEHOLDER_SVG,
    { status: 200, headers: { "Content-Type": "image/svg+xml" } });

  const respond = (e) => {
    if (e.kind === "binary") return svgResponse();
    return new Response(
      e.kind === "json" ? JSON.stringify(e.body) : (e.body ?? ""),
      { status: e.status, headers: { "Content-Type": e.kind === "json"
          ? "application/json" : "text/plain" } });
  };

  window.fetch = async (input, init = {}) => {
    const url = typeof input === "string" ? input : input.url;
    const method = ((init && init.method) ||
                    (typeof input === "object" && input.method) ||
                    "GET").toUpperCase();

    if (!url.startsWith("/api/")) {
      // Rendered files (panels, boards, previews) live outside /api/ and
      // are not in the bundle by design — the harness audits layout,
      // states, type and chrome, not imagery. Loud placeholder, so a
      // missing fixture is never mistaken for a design decision.
      if (IMG_RE.test(url)) return svgResponse();
      console.warn("[harness] non-api fetch, 404:", url);
      return new Response("", { status: 404 });
    }

    const key = `${method} ${url}`;
    const list = byKey.get(key);
    if (list) {
      // Replay repeated GETs in recorded order, then hold the last.
      const i = Math.min(cursor.get(key) || 0, list.length - 1);
      cursor.set(key, i + 1);
      return respond(list[i]);
    }

    // A mutation nobody recorded: succeed emptily so the UI proceeds,
    // and log it loudly. A silent 200 would let a broken flow look fine.
    if (method !== "GET") {
      console.warn("[harness] unrecorded mutation, no-op:", key);
      MISSES.push(key);
      return new Response("{}",
        { status: 200, headers: { "Content-Type": "application/json" } });
    }

    // An unrecorded GET is the honest failure: the screen was never walked.
    console.warn("[harness] MISS:", key);
    MISSES.push(key);
    return new Response(
      JSON.stringify({ detail: `harness: no fixture for ${key}` }),
      { status: 404, headers: { "Content-Type": "application/json" } });
  };

  const onReady = (fn) => document.readyState === "loading"
    ? document.addEventListener("DOMContentLoaded", fn) : fn();

  // <img> tags never pass through fetch — catch their 404s in the
  // capture phase and swap in the placeholder file.
  onReady(() => {
    document.body.addEventListener("error", (ev) => {
      const t = ev.target;
      if (t && t.tagName === "IMG" &&
          !t.src.endsWith("icons/harness-placeholder.svg")) {
        t.src = "icons/harness-placeholder.svg";
      }
    }, true);

    // Staleness banner: a harness that lies about its own age is worse
    // than no harness. Non-dismissible by design.
    if (BUNDLE.app_sha !== HARNESS.harness_sha) {
      const bar = document.createElement("div");
      bar.id = "harness-stale";
      bar.textContent = `FIXTURES RECORDED AGAINST ${BUNDLE.app_sha} · ` +
        `HARNESS APP.JS IS ${HARNESS.harness_sha} · RE-RECORD`;
      bar.style.cssText = [
        "position:fixed", "top:0", "left:0", "right:0", "z-index:99999",
        "font-family:var(--mono)", "font-size:12px", "letter-spacing:.5px",
        "color:var(--bad)", "background:var(--panel)",
        "border-bottom:1px solid var(--bad-line)", "padding:8px 14px",
      ].join(";");
      document.body.prepend(bar);
    }
  });
})();
"""

PLACEHOLDER_SVG = """<svg xmlns="http://www.w3.org/2000/svg" width="800" height="450" viewBox="0 0 800 450"><rect width="800" height="450" fill="{panel}"/><text x="400" y="225" fill="{ink}" font-family="Courier New, Courier, monospace" font-size="20" letter-spacing="2" text-anchor="middle" dominant-baseline="middle">NO FIXTURE IMAGE</text></svg>"""


def token_hex(css: str, name: str, fallback: str) -> str:
    m = re.search(re.escape(name) + r":\s*(#[0-9a-fA-F]{3,8})", css)
    return m.group(1) if m else fallback


def harness_sha() -> str:
    try:
        r = subprocess.run(["git", "rev-parse", "--short", "HEAD"],
                           cwd=str(ROOT), capture_output=True, text=True,
                           timeout=5)
        if r.returncode == 0 and r.stdout.strip():
            return r.stdout.strip()
    except Exception:
        pass
    return "unknown"


def api_routes(main_py_text: str) -> list[tuple[str, str]]:
    """Every /api/ route declared in main.py, as (METHOD, template)."""
    routes = []
    for m in re.finditer(
            r'@app\.(get|post|put|delete|patch)\(\s*"(/api/[^"]*)"',
            main_py_text):
        routes.append((m.group(1).upper(), m.group(2)))
    return routes


def route_regex(template: str) -> re.Pattern:
    parts = re.split(r"({[^}]+})", template)
    pat = "".join("[^/]+" if p.startswith("{") else re.escape(p)
                  for p in parts if p)
    return re.compile(pat + r"\Z")


def coverage(bundle: dict, routes: list[tuple[str, str]]) -> list[str]:
    """The /api/ routes the bundle does not cover — the honest report of
    what the recording walk missed."""
    recorded = set()
    for e in bundle.get("entries", []):
        path = e["url"].split("?", 1)[0].split("#", 1)[0]
        recorded.add((e["method"].upper(), path))
    uncovered = []
    for method, template in routes:
        rx = route_regex(template)
        if not any(m == method and rx.match(p) for m, p in recorded):
            uncovered.append(f"{method} {template}")
    return uncovered


def rewrite_index(html: str) -> str:
    """Server-absolute refs -> relative, and the fixture scripts inserted
    before app.js. The ONLY edits the harness copy of index.html gets."""
    html = html.replace('href="/styles.css"', 'href="styles.css"')
    html = html.replace('src="/app.js"', 'src="app.js"')
    html = html.replace('"/icons/', '"icons/')
    needle = '<script src="app.js"></script>'
    if needle not in html:
        raise SystemExit("index.html: app.js script tag not found — "
                         "the shell changed shape; update build_harness.py")
    html = html.replace(needle,
                        '<script src="fixtures.data.js"></script>\n'
                        '<script src="fixtures.js"></script>\n' + needle)
    return html


def build(bundle_path: Path, out: Path) -> dict:
    bundle = json.loads(bundle_path.read_text(encoding="utf-8"))
    if "entries" not in bundle:
        raise SystemExit(f"{bundle_path}: not a recorder bundle "
                         "(no 'entries') — record one with ?record=1")

    out.mkdir(parents=True, exist_ok=True)

    # 1. shipped code, byte-identical
    shutil.copy2(STATIC / "app.js", out / "app.js")
    shutil.copy2(STATIC / "styles.css", out / "styles.css")
    if (out / "icons").exists():
        shutil.rmtree(out / "icons")
    shutil.copytree(STATIC / "icons", out / "icons")

    # 2. the placeholder, in concrete hex lifted from the shipped tokens
    css = (STATIC / "styles.css").read_text(encoding="utf-8")
    svg = PLACEHOLDER_SVG.format(panel=token_hex(css, "--panel", "#1a1d21"),
                                 ink=token_hex(css, "--ink-faint", "#6b7278"))
    (out / "icons" / "harness-placeholder.svg").write_text(svg,
                                                           encoding="utf-8")

    # 3. index.html, rewritten
    html = (STATIC / "index.html").read_text(encoding="utf-8")
    (out / "index.html").write_text(rewrite_index(html), encoding="utf-8")

    # 4. fixtures — as .js, because a file: origin cannot fetch() a bare
    #    fixtures.json
    sha = harness_sha()
    manifest = {
        "app_sha": bundle.get("app_sha", "unknown"),
        "recorded_at": bundle.get("recorded_at", ""),
        "project_slug": bundle.get("project_slug", ""),
        "entry_count": len(bundle["entries"]),
        "harness_sha": sha,
    }
    (out / "fixtures.data.js").write_text(
        "window.__FIXTURES__ = " + json.dumps(bundle) + ";\n"
        "window.__HARNESS__ = " + json.dumps({"harness_sha": sha}) + ";\n",
        encoding="utf-8")
    (out / "fixtures.js").write_text(
        FIXTURES_JS.replace("%%PLACEHOLDER_SVG%%", json.dumps(svg)),
        encoding="utf-8")
    (out / "MANIFEST.json").write_text(json.dumps(manifest, indent=2) + "\n",
                                       encoding="utf-8")
    return manifest


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("bundle", type=Path, help="recorded fixtures-*.json")
    ap.add_argument("--out", type=Path, default=ROOT / "harness")
    args = ap.parse_args(argv)

    manifest = build(args.bundle, args.out)
    bundle = json.loads(args.bundle.read_text(encoding="utf-8"))
    entries = bundle["entries"]
    distinct = {e["key"] for e in entries}
    missed = coverage(bundle, api_routes(MAIN_PY.read_text(encoding="utf-8")))

    print(f"harness: {args.out}")
    print(f"  app_sha (fixtures): {manifest['app_sha']}"
          f"   harness_sha: {manifest['harness_sha']}")
    print(f"  entries: {len(entries)}   distinct endpoints: {len(distinct)}")
    print(f"  /api/ routes in main.py NOT covered by this bundle "
          f"({len(missed)}):")
    for r in missed:
        print(f"    {r}")
    if not missed:
        print("    (none — every declared route was walked)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
